#!/bin/bash

IAT_ORIG=$IAT_MODE
LISTEN_ORIG=$LISTEN_ADDRESS
REDIRECT_ORIG=$REDIRECT_TO

source /var/tor/envvars

export TOR_PT_SERVER_TRANSPORTS=obfs4
export TOR_PT_CLIENT_TRANSPORTS=obfs4
export TOR_PT_SERVER_TRANSPORT_OPTIONS=obfs4:iat-mode=${IAT_ORIG:-$IAT_MODE}
export TOR_PT_SERVER_BINDADDR=obfs4-${LISTEN_ORIG:-$LISTEN_ADDRESS}
export TOR_PT_ORPORT=${REDIRECT_ORIG:-$REDIRECT_TO}

show_help() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  -s, --server     Obfs4proxy will run in server mode. Server settings can be configured by modifying the variables in the /var/tor/envvars file"
    echo "  -c, --client     Obfs4proxy will run in client mode"
    echo "  -h, --help       Shows this help"
    echo "  -v, --version    Shows the obfs4proxy program version"
}

if [[ -z $1 ]]; then
    show_help
    exit 0
fi

case $1 in
    -s|--server)
        unset TOR_PT_CLIENT_TRANSPORTS
        obfs4proxy -enableLogging -logLevel DEBUG
        exit 0
        ;;
    -c|--client)
        unset TOR_PT_SERVER_TRANSPORTS TOR_PT_SERVER_TRANSPORT_OPTIONS TOR_PT_SERVER_BINDADDR TOR_PT_ORPORT
        obfs4proxy -enableLogging -logLevel DEBUG
        exit 0
        ;;
    -v|--version)
        obfs4proxy --version
        exit 0
        ;;
    -h|--help|*)
        show_help
        exit 0
        ;;
esac

